export type {
  DSLStyle,
  DSLStyles,
  DSLNodeType,
  DSLLayoutStyle,
  DSLBaseNode,
  DSLFrameNode,
  DSLInstanceNode,
  DSLTextNode,
  DSLPathItem,
  DSLPathNode,
  DSLGroupNode,
  DSLLayerNode,
  DSLNode,
  DSLData,
  DesignData as DesignData,
  StyleValue,
  ImageValue,
  LayerStyle,
} from '@fta/shared-types';
